name: DB migrations


on:
  push:
    branches:
      - "*"


env:
  CI: true
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASS: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_REG: docker.pkg.github.com


jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Code analysis
        run: ./run_static_analysis.sh

      - name: Dependency audit
        run: ./run_audit.sh


  test:
    name: Unit test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Unit tests
        run: ./run_unit_tests.sh


  system_test:
    name: System test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: System tests
        run: ./run_system_tests.sh

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: robot-logs
          path: logs


  stories:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    needs: [check, test, system_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "@todo deploy"
